In [1]:
import pandas as pd
d=pd.read_excel("last.xlsx")
d

Rainfall(mm)  Minimum Temparature(C)  Maximum Temperature (C)    Ph  \
0       156.040000               29.100000                    40.50  7.55   
1       165.740000               26.100000                    37.60  7.55   
2       240.520000               27.300000                    38.30  7.55   
3       180.180000               27.600000                    37.40  7.55   
4       256.060000               25.380000                    39.94  7.55   
...            ...                     ...                      ...   ...   
1131     15.042900                9.600000                    44.90  5.50   
1132      5.171429               28.300000                    41.80  6.54   
1133     11.285714               20.000000                    35.10  6.54   
1134      6.571429               20.166667                    40.70  6.54   
1135     11.271429               12.200000                    45.20  6.54   

      N(Kg/Hectar)  P(Kg/Hectar)  K(Kg/Hectar)  Zn(ppm)  Fe(ppm)  Cu(ppm)  \
0           180.00         17.60        284.00    1.350    14.00     0.58   
1           180.00         17.60        284.00    1.350    14.00     0.58   
2           180.00         17.60        284.00    1.350    14.00     0.58   
3           180.00         17.60        284.00    1.350    14.00     0.58   
4           180.00         17.60        284.00    1.350    14.00     0.58   
...            ...           ...           ...      ...      ...      ...   
1131        162.69         18.08        215.84    1.833     4.67     2.76   
1132        170.70         34.10        283.10    3.200     8.30     1.60   
1133        170.70         34.10        283.10    3.200     8.30     1.60   
1134        170.70         34.10        283.10    3.200     8.30     1.60   
1135        170.70         34.10        283.10    3.200     8.30     1.60   

      ...  District_Warangal  District_Warangal urban  District_Yadadri  \
0     ...                  0                        0                 0   
1     ...                  0                        0                 0   
2     ...                  0                        0                 0   
3     ...                  0                        0                 0   
4     ...                  0                        0                 0   
...   ...                ...                      ...               ...   
1131  ...                  0                        1                 0   
1132  ...                  0                        0                 1   
1133  ...                  0                        0                 1   
1134  ...                  0                        0                 1   
1135  ...                  0                        0                 1   

      Season_Kharif  Season_rabi  Crop_Groundnut  Crop_Maize  \
0                 1            0               0           0   
1                 1            0               0           0   
2                 1            0               0           0   
3                 1            0               0           0   
4                 1            0               0           0   
...             ...          ...             ...         ...   
1131              0            1               0           0   
1132              0            1               0           0   
1133              0            1               0           0   
1134              0            1               0           0   
1135              0            1               0           0   

      Crop_Moong(Green Gram)  Crop_Rice  Crop_cotton(lint)  
0                          0          0                  1  
1                          0          0                  1  
2                          0          0                  1  
3                          0          0                  1  
4                          0          0                  1  
...                      ...        ...                ...  
1131                       0          1                  0 

In [2]:
d.columns

Index(['Rainfall(mm)', 'Minimum Temparature(C)', 'Maximum Temperature (C)',
       'Ph', 'N(Kg/Hectar)', 'P(Kg/Hectar)', 'K(Kg/Hectar)', 'Zn(ppm)',
       'Fe(ppm)', 'Cu(ppm)', 'Mn(ppm)', 'Irrigation(MBGL)',
       'Yield (Bales/Hectare)', 'District_Adilabad', 'District_Bhadradri',
       'District_Jagitial', 'District_Jangoan', 'District_Jayashankar',
       'District_Jogulamba', 'District_Kamareddy', 'District_Karimnagar',
       'District_Khammam', 'District_Komaram bheem asifabad',
       'District_Mahabubabad', 'District_Mahbubnagar', 'District_Mancherial',
       'District_Medak', 'District_Medchal', 'District_Mulugu',
       'District_Nagarkurnool', 'District_Nalgonda', 'District_Narayanapet',
       'District_Nirmal', 'District_Nizamabad', 'District_Peddapalli',
       'District_Rajanna', 'District_Rangareddy', 'District_Sangareddy',
       'District_Siddipet', 'District_Suryapet', 'District_Vikarabad',
       'District_Wanaparthy', 'District_Warangal', 'District_Warangal urban

In [3]:
y=d['Yield (Bales/Hectare)'].values
x=d.drop('Yield (Bales/Hectare)',axis=1).values
x

array([[156.04      ,  29.1       ,  40.5       , ...,   0.        ,
          0.        ,   1.        ],
       [165.74      ,  26.1       ,  37.6       , ...,   0.        ,
          0.        ,   1.        ],
       [240.52      ,  27.3       ,  38.3       , ...,   0.        ,
          0.        ,   1.        ],
       ...,
       [ 11.28571429,  20.        ,  35.1       , ...,   0.        ,
          1.        ,   0.        ],
       [  6.57142857,  20.16666667,  40.7       , ...,   0.        ,
          1.        ,   0.        ],
       [ 11.27142857,  12.2       ,  45.2       , ...,   0.        ,
          1.        ,   0.        ]])

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [8]:
#neural network model using the Keras library
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import r2_score


# Standardize the features
# scaler = StandardScaler()
# X_train = scaler.fit_transform(x_train)
# X_test = scaler.transform(x_test)

# Initialize and train the neural network model
model = Sequential()
model.add(Dense(64, activation='relu', input_dim=x_train.shape[1]))
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation='linear'))
model.compile(loss='mean_squared_error', optimizer='adam')

model.fit(x_train, y_train, epochs=100, batch_size=32)

# Predict on the test set
y_pred = model.predict(x_test)

# Evaluate the model
r2 = r2_score(y_test, y_pred)
print('R2 Score:', r2)


Epoch 1/100
29/29 [==============================] - 1s 4ms/step - loss: 180.0736
Epoch 2/100
29/29 [==============================] - 0s 4ms/step - loss: 15.3923
Epoch 3/100
29/29 [==============================] - 0s 3ms/step - loss: 7.2610
Epoch 4/100
29/29 [==============================] - 0s 4ms/step - loss: 5.2392
Epoch 5/100
29/29 [==============================] - 0s 4ms/step - loss: 4.5452
Epoch 6/100
29/29 [==============================] - 0s 3ms/step - loss: 4.1162
Epoch 7/100
29/29 [==============================] - 0s 3ms/step - loss: 4.1851
Epoch 8/100
29/29 [==============================] - 0s 3ms/step - loss: 4.3763
Epoch 9/100
29/29 [==============================] - 0s 3ms/step - loss: 3.7147
Epoch 10/100
29/29 [==============================] - 0s 3ms/step - loss: 3.3455
Epoch 11/100
29/29 [==============================] - 0s 4ms/step - loss: 3.2516
Epoch 12/100
29/29 [==============================] - 0s 5ms/step - loss: 3.1789
Epoch 13/100
29/29 [==============

In [ ]:
x_test[0]

array([134.92,  19.  ,  44.1 ,   7.51, 196.4 ,  54.9 , 231.2 ,   1.02,
        11.27,   1.45,   4.58,  19.93,   0.  ,   0.  ,   0.  ,   0.  ,
         0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,
         0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,
         0.  ,   0.  ,   0.  ,   1.  ,   0.  ,   0.  ,   0.  ,   0.  ,
         0.  ,   0.  ,   0.  ,   0.  ,   1.  ,   0.  ,   0.  ,   1.  ,
         0.  ,   0.  ,   0.  ])

In [ ]:
from tensorflow.python.saved_model.save import save
model.save("/content/model.h5")

In [ ]:
!pip3 install tensorflowjs

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!tensorflowjs_converter --input_format=keras --output_format=tfjs_layers_model /content/model.h5 /content

2023-06-22 04:41:23.067288: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
rf=RandomForestRegressor()
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
print("r2_score",r2_score(y_test,y_pred))
print("mean_sq_err",mean_squared_error(y_test,y_pred))

r2_score 0.8338982010747373
mean_sq_err 0.6074594348526782


In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error


# Convert data to numpy arrays
X_train = np.array(x_train)
y_train = np.array(y_train)
X_test = np.array(x_test)
y_test = np.array(y_test)

# Reshape the input data to (samples, timesteps, features)
n_samples = X_train.shape[0]
n_timesteps = 1
n_features = X_train.shape[1]
X_train = X_train.reshape((n_samples, n_timesteps, n_features))
X_test = X_test.reshape((X_test.shape[0], n_timesteps, n_features))

# Define the RNN model
model = tf.keras.models.Sequential([
    tf.keras.layers.SimpleRNN(64, input_shape=(n_timesteps, n_features)),
    tf.keras.layers.Dense(1)
])

# Compile the model
model.compile(optimizer='adam', loss='mse')

# Train the model
model.fit(X_train, y_train, epochs=230, batch_size=32)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
r2 = r2_score(y_test, y_pred)
print('R2 Score:', r2)
print("mean squared error:",mean_squared_error(y_test, y_pred))

Epoch 1/230
28/28 [==============================] - 1s 2ms/step - loss: 7.5624
Epoch 2/230
28/28 [==============================] - 0s 2ms/step - loss: 3.7206
Epoch 3/230
28/28 [==============================] - 0s 3ms/step - loss: 3.6070
Epoch 4/230
28/28 [==============================] - 0s 3ms/step - loss: 3.6114
Epoch 5/230
28/28 [==============================] - 0s 3ms/step - loss: 3.5861
Epoch 6/230
28/28 [==============================] - 0s 2ms/step - loss: 3.5568
Epoch 7/230
28/28 [==============================] - 0s 2ms/step - loss: 3.5579
Epoch 8/230
28/28 [==============================] - 0s 2ms/step - loss: 3.5320
Epoch 9/230
28/28 [==============================] - 0s 2ms/step - loss: 3.5516
Epoch 10/230
28/28 [==============================] - 0s 1ms/step - loss: 3.5343
Epoch 11/230
28/28 [==============================] - 0s 1ms/step - loss: 3.5224
Epoch 12/230
28/28 [==============================] - 0s 2ms/step - loss: 3.5064
Epoch 13/230
28/28 [=================

In [ ]:
len(X_test[0][0])

51

In [ ]:
model.predict(x_test[0].reshape(1,1,51))

1/1 [==============================] - 0s 157ms/step


array([[3.6941369]], dtype=float32)

In [ ]:
from tensorflow.python.saved_model.save import save
model.save("/content/model.h5")

In [ ]:
!tensorflowjs_converter --input_format=keras --output_format=tfjs_layers_model /content/model.h5 /content #bin file

2023-06-22 04:54:29.566985: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
